- hosts: localhost
  become: true
  tasks:
    - name: Cloning .dotfiles
      ansible.builtin.git:
        repo: https://github.com/andreferrazz/.dotfiles.git
        dest: /home/andre/.dotfiles
        recursive: yes
        update: yes
        version: main
      become_user: andre
      tags:
        - dotfiles
    - name: Create .config
      ansible.builtin.file:
        path: ~/.config
        state: directory
      become_user: andre
      tags:
        - dotfiles
    - name: Link .zshrc
      ansible.builtin.file:
        src: ~/.dotfiles/.zshrc
        dest: ~/.zshrc
        state: link
      become_user: andre
      tags:
        - dotfiles
    - name: Link nvim config
      ansible.builtin.file:
        src: ~/.dotfiles/.config/nvim
        dest: ~/.config/nvim
        state: link
      become_user: andre
      tags:
        - dotfiles
    - name: Install fontconfig
      apt: name=fontconfig
    - name: Create nerd fonts folder
      shell: mkdir ~/.nerd-fonts 
      become_user: andre
    - name: Clone nerd fonts folder
      shell: git clone --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts.git ~/.nerd-fonts/ 
      become_user: andre
    - name: Sparse Checkout JetBrainsMono
      shell: cd ~/.nerd-fonts && git sparse-checkout add patched-fonts/JetBrainsMono 
      become_user: andre
    - name: Install JetBrainsMono Nerd Font
      shell: ~/.nerd-fonts/install.sh JetBrainsMono
      become_user: andre
    - name: Install zsh
      apt: name=zsh
    - name: Change shell to zsh
      shell: chsh -s $(which zsh)
    - name: Install starship
      shell: curl -sS https://starship.rs/install.sh | sh -s -- --yes
    - name: Config starship
      shell: starship preset gruvbox-rainbow -o ~/.config/starship.toml
      become_user: andre
    - name: Install Neovim
      apt: name=neovim

